# Generated by Django 5.2.4 on 2025-08-06 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('DINING_OUT', 'Dining Out'), ('TRANSPORTATION', 'Transportation'), ('HOUSING', 'Housing'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('payment_method', models.CharField(choices=[('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'date'], name='expenses_ex_owner_i_d056f1_idx'), models.Index(fields=['owner', 'category'], name='expenses_ex_owner_i_87b7d5_idx')],
            },
        ),
    ]
