# Generated by Django 5.2.7 on 2026-07-13 18:49

import django.core.validators
import expenses.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(validators=[expenses.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
